apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-deployment
  labels:
    app: my-app
    type: frontend
    environment: dev

spec:
  replicas: 5

  selector:
    matchLabels:
      app: my-app
      type: frontend
      environment: dev

  template:
    metadata:
      labels:
        app: my-app
        type: frontend
        environment: dev

    spec:
      containers:
      - name: nginx-cont
        image: nginx:latest
  